apiVersion: v1
kind: ReplicationController
metadata:
  name: dispatch-bot
spec:
  replicas: 1
  selector:
    app: dispatch-bot
  template:
    metadata:
      name: dispatch-bot
      labels:
        app: dispatch-bot
    spec:
      containers:
      - name: dispatch-bot
        image: us.gcr.io/peppy-vertex-163516/dispatch-notify-bot
        env:
        - name: BOT_TOKEN
          value: ""
