apiVersion: v1
kind: Service
metadata:
  name: resume
  labels:
    app: resume
spec:
  # Create a static address with the "gcloud compute addresses" command
  loadBalancerIP: "35.225.12.94"
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: resume
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: resume
spec:
  replicas: 1
  selector:
    app: resume
  template:
    metadata:
      name: resume
      labels:
        app: resume
    spec:
      containers:
      - name: apache
        image: us.gcr.io/peppy-vertex-163516/resume
        ports:
        - containerPort: 80
