apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: mongo-data
spec:
  capacity:
    storage: "20Gi"
  accessModes:
    - "ReadWriteOnce"
  gcePersistentDisk:
    fsType: "ext4"
    pdName: "mongo-disk"
